name = "ArrayTools"
uuid = "1dc0ca97-c5ce-4e77-ac6d-c576ac9d7f27"
authors = ["Éric Thiébaut <eric.thiebaut@univ-lyon1.fr>"]
version = "0.1.0"

[compat]
julia = "1.0, 1.1, 1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
